services:
  devcontainer:
    build: 
      context: .
      dockerfile: devcontainer.Dockerfile
    volumes:
      - ../:/workspace:cached
      - ${HOME}/.ssh:/home/node/.ssh:ro
      
    command: sleep infinity
    env_file:
      - .env.devcontainer
    depends_on:
      - db
  
  db:
    image: postgres:latest
    env_file:
      - .env.db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: